language: ruby

rvm:
  - 2.3.1

services:
  - mysql

bundler_args: "--without development --deployment"

cache: bundler

berire_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:setup

script:
  - bundle exec rake test
