language: ruby

rvm:
  - 2.3.1

services:
  - mysql

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:setup

notifications:
  email: false
