language: ruby

rvm:
  - 2.3.1

services:
  - mysql

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  # MySQL5.7をインストール
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:setup

notifications:
  email: false
