# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2160bed0b03f4a8b930f9c9521a9bd54606d3331ff08a4af9e838b24ba20aa633df74dc1471bef697adda0e506726d1ae05a6b803a0daaae9832c0231c1981

test:
  secret_key_base: 08bbd55b1330a3624eb708f47755f17c99baaeea9d691544f265128d751158abbb1096e0bce13df673344969966738c418479eab7f243d435f0c8237d895f73e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
